services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  envoy:
    build:
      context: ./envoy
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
  usersrv:
    build:
      context: ./server/usersrv
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
  modelsrv:
    build:
      context: ./server/modelsrv
      dockerfile: dockerfile
    ports:
      - "9001:9001"
    depends_on:
      postgres:
        condition: service_healthy
  approxsrv:
    build:
      context: ./server/approxsrv
      dockerfile: dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - envoy
      - postgres
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
volumes:
  postgres:
