services:
  client_svc:
    build:
      context: ./services/ClientService
    ports:
      - "80:80"
    restart: always
  envoy:
    build:
      context: ./envoy
    ports:
      - "8080:8080"
    restart: always
  api_svc:
    build:
      context: ./services/ApiService
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - auth_svc
      - user_svc
      - model_svc
      - approx_svc
    volumes:
      - ./envoy/api-envoy.yaml:/etc/api-envoy.yaml
    environment:
      PORT: ':9090'
      AUTH_ADDR: 'auth_svc:9091'
      USER_ADDR: 'user_svc:9092'
      MODEL_ADDR: 'model_svc:9093'
      APPROX_ADDR: 'approx_svc:9094'
  auth_svc:
    build:
      context: ./services/AuthService
    restart: always
    environment:
      PORT: ':9091'
  user_svc:
    build:
      context: ./services/UserService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: ':9092'
      DB_HOST: 'postgres'
      DB_USER: 'approx_user'
      DB_PASS: 'user_pass'
      DB_NAME: 'approx_tool'
      DB_PORT: '5432'
  model_svc:
    build:
      context: ./services/ModelService
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: ':9093'
      DB_HOST: 'postgres'
      DB_USER: 'approx_model'
      DB_PASS: 'model_pass'
      DB_NAME: 'approx_tool'
      DB_PORT: '5432'
  approx_svc:
    build:
      context: ./services/ApproxService
    deploy:
      replicas: 1
    environment:
      PORT: ':9094'
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./database/initialization/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/initialization/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
