# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: approximation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='approximation.proto',
  package='approximationService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61pproximation.proto\x12\x14\x61pproximationService\"8\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x0e\n\x06stderr\x18\x03 \x01(\x02\"\xac\x02\n\tFitResult\x12\x16\n\x0esuccess_status\x18\x01 \x01(\x08\x12\t\n\x01r\x18\x02 \x01(\x02\x12\x0e\n\x06r_sqrt\x18\x03 \x01(\x02\x12\x0b\n\x03\x61ic\x18\x04 \x01(\x02\x12\x0b\n\x03\x62ic\x18\x05 \x01(\x02\x12\x0b\n\x03\x66og\x18\x06 \x01(\x05\x12\x11\n\tmean_of_x\x18\x07 \x01(\x02\x12\x11\n\tmean_of_y\x18\x08 \x01(\x02\x12\x10\n\x08\x63hi_sqrt\x18\t \x01(\x02\x12\x18\n\x10reduced_chi_sqrt\x18\n \x01(\x02\x12\x13\n\x0b\x64\x61ta_points\x18\x0b \x01(\x02\x12\x16\n\x0e\x66itting_method\x18\x0c \x01(\t\x12\x32\n\tparameter\x18\r \x03(\x0b\x32\x1f.approximationService.Parameter\x12\x12\n\nmodel_name\x18\x0e \x01(\t\"F\n\x0f\x43urveFitRequest\x12\x0e\n\x06x_data\x18\x01 \x03(\x02\x12\x0e\n\x06y_data\x18\x02 \x03(\x02\x12\x13\n\x0b\x65xpressions\x18\x03 \x03(\t\"E\n\x0e\x43urveFitResult\x12\x33\n\nfit_result\x18\x01 \x03(\x0b\x32\x1f.approximationService.FitResult2p\n\x14\x41pproximationService\x12X\n\tFitCurves\x12%.approximationService.CurveFitRequest\x1a$.approximationService.CurveFitResultb\x06proto3'
)




_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='approximationService.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='approximationService.Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='approximationService.Parameter.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='approximationService.Parameter.stderr', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=101,
)


_FITRESULT = _descriptor.Descriptor(
  name='FitResult',
  full_name='approximationService.FitResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success_status', full_name='approximationService.FitResult.success_status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='approximationService.FitResult.r', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_sqrt', full_name='approximationService.FitResult.r_sqrt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aic', full_name='approximationService.FitResult.aic', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bic', full_name='approximationService.FitResult.bic', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fog', full_name='approximationService.FitResult.fog', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_of_x', full_name='approximationService.FitResult.mean_of_x', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_of_y', full_name='approximationService.FitResult.mean_of_y', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chi_sqrt', full_name='approximationService.FitResult.chi_sqrt', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reduced_chi_sqrt', full_name='approximationService.FitResult.reduced_chi_sqrt', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_points', full_name='approximationService.FitResult.data_points', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fitting_method', full_name='approximationService.FitResult.fitting_method', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='approximationService.FitResult.parameter', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='approximationService.FitResult.model_name', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=404,
)


_CURVEFITREQUEST = _descriptor.Descriptor(
  name='CurveFitRequest',
  full_name='approximationService.CurveFitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_data', full_name='approximationService.CurveFitRequest.x_data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_data', full_name='approximationService.CurveFitRequest.y_data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expressions', full_name='approximationService.CurveFitRequest.expressions', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=476,
)


_CURVEFITRESULT = _descriptor.Descriptor(
  name='CurveFitResult',
  full_name='approximationService.CurveFitResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fit_result', full_name='approximationService.CurveFitResult.fit_result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=547,
)

_FITRESULT.fields_by_name['parameter'].message_type = _PARAMETER
_CURVEFITRESULT.fields_by_name['fit_result'].message_type = _FITRESULT
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['FitResult'] = _FITRESULT
DESCRIPTOR.message_types_by_name['CurveFitRequest'] = _CURVEFITREQUEST
DESCRIPTOR.message_types_by_name['CurveFitResult'] = _CURVEFITRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'approximation_pb2'
  # @@protoc_insertion_point(class_scope:approximationService.Parameter)
  })
_sym_db.RegisterMessage(Parameter)

FitResult = _reflection.GeneratedProtocolMessageType('FitResult', (_message.Message,), {
  'DESCRIPTOR' : _FITRESULT,
  '__module__' : 'approximation_pb2'
  # @@protoc_insertion_point(class_scope:approximationService.FitResult)
  })
_sym_db.RegisterMessage(FitResult)

CurveFitRequest = _reflection.GeneratedProtocolMessageType('CurveFitRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURVEFITREQUEST,
  '__module__' : 'approximation_pb2'
  # @@protoc_insertion_point(class_scope:approximationService.CurveFitRequest)
  })
_sym_db.RegisterMessage(CurveFitRequest)

CurveFitResult = _reflection.GeneratedProtocolMessageType('CurveFitResult', (_message.Message,), {
  'DESCRIPTOR' : _CURVEFITRESULT,
  '__module__' : 'approximation_pb2'
  # @@protoc_insertion_point(class_scope:approximationService.CurveFitResult)
  })
_sym_db.RegisterMessage(CurveFitResult)



_APPROXIMATIONSERVICE = _descriptor.ServiceDescriptor(
  name='ApproximationService',
  full_name='approximationService.ApproximationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=549,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='FitCurves',
    full_name='approximationService.ApproximationService.FitCurves',
    index=0,
    containing_service=None,
    input_type=_CURVEFITREQUEST,
    output_type=_CURVEFITRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPROXIMATIONSERVICE)

DESCRIPTOR.services_by_name['ApproximationService'] = _APPROXIMATIONSERVICE

# @@protoc_insertion_point(module_scope)
